project:
  type: website
  output-dir: _site


website:
  title: "Taxable income viewer (v0.1)"
  navbar:
    left:
      - text: "Home"
        href: "home.qmd"
      - text: "Mean value"
        href: "data.qmd"
      - text: "Record number"
        href: "data_src.qmd"
      - text: "Download"
        href: "table.qmd"
    right:
      - text: "Contact"
        href: "contact.qmd"

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
