project:
  type: website
  output-dir: _site


website:
  title: "Taxable income viewer (v0.2)"
  navbar:
    left:
      - text: "Home"
        href: "home.qmd"
      - text: "Income (Mean)"
        href: "data.qmd"
      - text: "Income (Ratio)"
        href: "ratio.qmd"
      - text: "Data source"
        href: "data_src.qmd"
      - text: "Download"
        href: "table.qmd"
    right:
      - text: "Contact"
        href: "contact.qmd"

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
